// SPDX-FileCopyrightText: 2019 DamianX
// SPDX-FileCopyrightText: 2019 ZelteHonor
// SPDX-FileCopyrightText: 2021 Acruid
// SPDX-FileCopyrightText: 2021 DrSmugleaf
// SPDX-FileCopyrightText: 2021 Swept
// SPDX-FileCopyrightText: 2021 mirrorcult
// SPDX-FileCopyrightText: 2022 Andreas Kämper
// SPDX-FileCopyrightText: 2022 Fishfish458
// SPDX-FileCopyrightText: 2022 Flipp Syder
// SPDX-FileCopyrightText: 2022 Paul Ritter
// SPDX-FileCopyrightText: 2022 fishfish458 <fishfish458>
// SPDX-FileCopyrightText: 2022 wrexbe
// SPDX-FileCopyrightText: 2023 Checkraze
// SPDX-FileCopyrightText: 2023 Dvir
// SPDX-FileCopyrightText: 2023 Nemanja
// SPDX-FileCopyrightText: 2023 ike709
// SPDX-FileCopyrightText: 2023 metalgearsloth
// SPDX-FileCopyrightText: 2024 Cojoke
// SPDX-FileCopyrightText: 2024 GreaseMonk
// SPDX-FileCopyrightText: 2024 James Simonson
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers
// SPDX-FileCopyrightText: 2024 Tayrtahn
// SPDX-FileCopyrightText: 2024 Whatstone
// SPDX-FileCopyrightText: 2024 Winkarst
// SPDX-FileCopyrightText: 2024 checkraze
// SPDX-FileCopyrightText: 2025 Redrover1760
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared.VendingMachines;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Content.Shared._NF.Bank; // Frontier
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;
using Robust.Client.UserInterface;
using Content.Client.UserInterface.Controls;
using Content.Shared.IdentityManagement;
using Robust.Client.Graphics;
using Robust.Shared.Utility;

namespace Content.Client.VendingMachines.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class VendingMachineMenu : FancyWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly IEntityManager _entityManager = default!;

        private readonly Dictionary<EntProtoId, EntityUid> _dummies = [];
        private readonly Dictionary<EntProtoId, (ListContainerButton Button, VendingMachineItem Item)> _listItems = new();
        private readonly Dictionary<EntProtoId, uint> _amounts = new();

        /// <summary>
        /// Whether the vending machine is able to be interacted with or not.
        /// </summary>
        private bool _enabled;

        public event Action<GUIBoundKeyEventArgs, ListData>? OnItemSelected;

        public VendingMachineMenu()
        {
            MinSize = SetSize = new Vector2(250, 150);
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            VendingContents.SearchBar = SearchBar;
            VendingContents.DataFilterCondition += DataFilterCondition;
            VendingContents.GenerateItem += GenerateButton;
            VendingContents.ItemKeyBindDown += (args, data) => OnItemSelected?.Invoke(args, data);
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            // Don't clean up dummies during disposal or we'll just have to spawn them again
            if (!disposing)
                return;

            // Delete any dummy items we spawned
            foreach (var entity in _dummies.Values)
            {
                _entityManager.QueueDeleteEntity(entity);
            }
            _dummies.Clear();
        }

        private bool DataFilterCondition(string filter, ListData data)
        {
            if (data is not VendorItemsListData { ItemText: var text })
                return false;

            if (string.IsNullOrEmpty(filter))
                return true;

            return text.Contains(filter, StringComparison.CurrentCultureIgnoreCase);
        }

        private void GenerateButton(ListData data, ListContainerButton button)
        {
            if (data is not VendorItemsListData { ItemProtoID: var protoID, ItemText: var text })
                return;

            var item = new VendingMachineItem(protoID, text);
            _listItems[protoID] = (button, item);
            button.AddChild(item);
            button.AddStyleClass(StyleClass.ButtonSquare);
            button.Disabled = !_enabled || _amounts[protoID] == 0;
        }

        /// <summary>
        /// Populates the list of available items on the vending machine interface
        /// and sets icons based on their prototypes
        /// </summary>
        public void Populate(List<VendingMachineInventoryEntry> inventory, bool enabled,
            int balance, int? cashSlotBalance) // Frontier: add balance, cashSlotBalance
        {
            UpdateBalance(balance); // Frontier
            UpdateCashSlotBalance(cashSlotBalance); // Frontier
            _enabled = enabled;
            _listItems.Clear();
            _amounts.Clear();

            if (inventory.Count == 0 && VendingContents.Visible)
            {
                SearchBar.Visible = false;
                VendingContents.Visible = false;

                var outOfStockLabel = new Label()
                {
                    Text = Loc.GetString("vending-machine-component-try-eject-out-of-stock"),
                    Margin = new Thickness(4, 4),
                    HorizontalExpand = true,
                    VerticalAlignment = VAlignment.Stretch,
                    HorizontalAlignment = HAlignment.Center
                };

                MainContainer.AddChild(outOfStockLabel);

                SetSizeAfterUpdate(outOfStockLabel.Text.Length, 0);

                return;
            }

            var longestEntry = string.Empty;
            var listData = new List<VendorItemsListData>();

            for (var i = 0; i < inventory.Count; i++)
            {
                var entry = inventory[i];

                if (!_prototypeManager.Resolve(entry.ID, out var prototype))
                {
                    _amounts[entry.ID] = 0;
                    continue;
                }

                if (!_dummies.TryGetValue(entry.ID, out var dummy))
                {
                    dummy = _entityManager.Spawn(entry.ID);
                    _dummies.Add(entry.ID, dummy);
                }

                // Frontier START: item pricing
                // ok so we dont really have access to the pricing system so we are doing a quick price check
                // based on prototype info since the items inside a vending machine dont actually exist as entities
                // until they are spawned. So this little alg does the following:
                // first, checks for a staticprice component, and if it has one, checks to make sure its not 0 since
                // stacks and other items have 0 cost.
                // If the price is 0, then we check for both a stack price and a stack component, since if it has one
                // it should have the other too, and then calculates the price based on that.
                // If the price is still 0 or non-existant (this is the case for food and containers since their value is
                // determined dynamically by their contents/inventory), it then falls back to the default mystery
                // hardcoded value of 20xMarketModifier.
                var cost = 20;
                if (prototype != null && prototype.TryGetComponent<StaticPriceComponent>(out var priceComponent, _entityManager.ComponentFactory))
                {
                    if (priceComponent.Price != 0)
                    {
                        var price = (float)priceComponent.Price;
                        cost = (int)(price * priceModifier);
                    }
                    else
                    {
                        if (prototype.TryGetComponent<StackPriceComponent>(out var stackPrice, _entityManager.ComponentFactory)
                            && prototype.TryGetComponent<StackComponent>(out var stack, _entityManager.ComponentFactory))
                        {
                            var price = stackPrice.Price * stack.Count;
                            cost = (int)(price * priceModifier);
                        }
                        else
                            cost = (int)(cost * priceModifier);
                    }
                }
                else
                    cost = (int)(cost * priceModifier);

                if (prototype != null && prototype.TryGetComponent<SolutionContainerManagerComponent>(out var priceSolutions, _entityManager.ComponentFactory))
                {
                    if (priceSolutions.Solutions != null)
                    {
                        foreach (var solution in priceSolutions.Solutions.Values)
                        {
                            foreach (var (reagent, quantity) in solution.Contents)
                            {
                                if (!_prototypeManager.Resolve(reagent.Prototype, out var reagentProto))
                                    continue;

                                // TODO check ReagentData for price information?
                                var costReagent = quantity.Float() * reagentProto.PricePerUnit;
                                cost += (int)(costReagent * priceModifier);
                            }
                        }
                    }
                }
                // Frontier END: item pricing

                // Frontier START: calculate vending price (this duplicates Content.Server.PricingSystem.GetVendPrice - this should be moved to Content.Shared if possible)
                if (prototype != null)
                {
                    var price = 0.0;

                    if (prototype.TryGetComponent<StaticPriceComponent>(out var staticComp, _entityManager.ComponentFactory) && staticComp.VendPrice > 0.0)
                    {
                        price += staticComp.VendPrice;
                    }
                    else if (prototype.TryGetComponent<StackPriceComponent>(out var stackComp, _entityManager.ComponentFactory) && stackComp.VendPrice > 0.0)
                    {
                        price += stackComp.VendPrice;
                    }

                    // If there is anything that explicitly sets vending price - higher OR lower, override the base.
                    if (price > 0.0)
                    {
                        cost = (int)price;
                    }
                }
                // Frontier END

                var itemName = Identity.Name(dummy, _entityManager);
                // Frontier START: unlimited vending
                //var itemText = $"{itemName} [{entry.Amount}]";
                //_amounts[entry.ID] = entry.Amount;
                String itemText;
                if (entry.Amount != uint.MaxValue){
                    itemText = $"[{BankSystemExtensions.ToSpesoString(cost)}] {itemName} [{entry.Amount}]";
                    _amounts[entry.ID] = entry.Amount;
                } else {
                    itemText = $"[{BankSystemExtensions.ToSpesoString(cost)}] {itemName}";
                }
                // Frontier END: unlimited vending


                if (itemText.Length > longestEntry.Length)
                    longestEntry = itemText;

                listData.Add(new VendorItemsListData(prototype.ID, i)
                {
                    ItemText = itemText,
                });
            }

            VendingContents.PopulateList(listData);

            SetSizeAfterUpdate(longestEntry.Length, inventory.Count);
        }

        /// <summary>
        /// Updates text entries for vending data in place without modifying the list controls.
        /// </summary>
        public void UpdateAmounts(List<VendingMachineInventoryEntry> cachedInventory, bool enabled)
        {
            _enabled = enabled;

            foreach (var proto in _dummies.Keys)
            {
                if (!_listItems.TryGetValue(proto, out var button))
                    continue;

                var dummy = _dummies[proto];
                if (!cachedInventory.TryFirstOrDefault(o => o.ID == proto, out var entry))
                    continue;
                var amount = entry.Amount;
                // Could be better? Problem is all inventory entries get squashed.
                var text = GetItemText(dummy, amount);

                button.Item.SetText(text);
                button.Button.Disabled = !enabled || amount == 0;
            }
        }

        private string GetItemText(EntityUid dummy, uint amount)
        {
            var itemName = Identity.Name(dummy, _entityManager);
            return $"{itemName} [{amount}]";
        }

        // Frontier START
        public void UpdateBalance(int balance)
        {
            BalanceLabel.Text = BankSystemExtensions.ToSpesoString(balance);
        }

        public void UpdateCashSlotBalance(int? balance)
        {
            CashSlotControls.Visible = balance != null;
            if (balance != null)
                CashSlotLabel.Text = BankSystemExtensions.ToSpesoString(balance.Value);
        }
        // Frontier END

        private void SetSizeAfterUpdate(int longestEntryLength, int contentCount)
        {
            SetSize = new Vector2(Math.Clamp((longestEntryLength + 2) * 12, 250, 400),
                Math.Clamp(contentCount * 50, 150, 350));
        }
    }

    public record VendorItemsListData(EntProtoId ItemProtoID, int ItemIndex) : ListData
    {
        public string ItemText = string.Empty;
    }
}
